apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-vc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: influxdb-v
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data_influxdb"