apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - port: 8086
      protocol: TCP