apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mysql
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
   - name: mysql
     image: mysql_img
     imagePullPolicy: Never
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: pass_db
     ports:
     - containerPort: 3306
       name: mysql
     volumeMounts:
     - name: mysql-persistent-storage
       mountPath: /var/lib/mysql
   volumes:
   - name: mysql-persistent-storage
     persistentVolumeClaim:
       claimName: mysql-vc
   - name: usermanagement-dbcreation-script
     configMap:
       name: usermanagement-dbcreation-script

             #  valueFrom:
      #   secretKeyRef:
      #     name: mysql-pass
      #     key: password
