apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
     app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana_img
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: user_grafana
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: pass_grafana
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-vc