apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftps
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftps-passive
      port: 21210
      targetPort: 21210
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
 selector:
  matchLabels:
   app: ftps
 template:
  metadata:
   labels:
    app: ftps
  spec:
   containers:
   - name: ftps
     image: ftps_img
     imagePullPolicy: Never
     ports:
     - containerPort: 21
     - containerPort: 21210